version: '3'
services:
  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: "Roooot1@"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
